spring:
  application:
    name: EasyRide

odsay:
  base-url: https://api.odsay.com/v1/api
  api-key:

sk:
  base-url: https://apis.openapi.sk.com/puzzle/subway
  api-key:

data-seoul:
  base-url: http://swopenAPI.seoul.go.kr/api/subway/{apiKey}/json
  api-key:
